export const browserCoreExamples = [
  "wukongbot browser status",
  "wukongbot browser start",
  "wukongbot browser stop",
  "wukongbot browser tabs",
  "wukongbot browser open https://example.com",
  "wukongbot browser focus abcd1234",
  "wukongbot browser close abcd1234",
  "wukongbot browser screenshot",
  "wukongbot browser screenshot --full-page",
  "wukongbot browser screenshot --ref 12",
  "wukongbot browser snapshot",
  "wukongbot browser snapshot --format aria --limit 200",
  "wukongbot browser snapshot --efficient",
  "wukongbot browser snapshot --labels",
];

export const browserActionExamples = [
  "wukongbot browser navigate https://example.com",
  "wukongbot browser resize 1280 720",
  "wukongbot browser click 12 --double",
  'wukongbot browser type 23 "hello" --submit',
  "wukongbot browser press Enter",
  "wukongbot browser hover 44",
  "wukongbot browser drag 10 11",
  "wukongbot browser select 9 OptionA OptionB",
  "wukongbot browser upload /tmp/file.pdf",
  'wukongbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "wukongbot browser dialog --accept",
  'wukongbot browser wait --text "Done"',
  "wukongbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "wukongbot browser console --level error",
  "wukongbot browser pdf",
];
